### ISSUE TITLE
Sftp.store: must use client.posix_rename

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borgstore#17]
Seems like rename works on openssh as we wanted, but not on other ssh servers (like the one on macOS).

We must use `client.posix_rename` to get the "overwrite destination" behavior.

**Comment by SpiritInAShell** [comment]
*May be (not) related*, only mentioned as a reference:

https://unix.stackexchange.com/a/123236

I mount most sshfs (FUSE) with the `sshfs ... -o workaround=rename` to solve "a similar problem".

True when I am accessing borg repos via sftp (Strato HiDrive, Hetzner Storagebox) (actually, I am using `workaround=rename` as default on any sshfs mount)

**Comment by ThomasWaldmann** [comment]
@SpiritInAShell Thanks for the hint, not sure it is related.

This is the code from paramiko the the 2 different renames:
```
    def rename(self, oldpath, newpath):
        """
        Rename a file or folder from ``oldpath`` to ``newpath``.

        .. note::
            This method implements 'standard' SFTP ``RENAME`` behavior; those
            seeking the OpenSSH "POSIX rename" extension behavior should use
            `posix_rename`.

        :param str oldpath:
            existing name of the file or folder
        :param str newpath:
            new name for the file or folder, must not exist already

        :raises:
            ``IOError`` -- if ``newpath`` is a folder, or something else goes
            wrong
        """
        oldpath = self._adjust_cwd(oldpath)
        newpath = self._adjust_cwd(newpath)
        self._log(DEBUG, "rename({!r}, {!r})".format(oldpath, newpath))
        self._request(CMD_RENAME, oldpath, newpath)

    def posix_rename(self, oldpath, newpath):
        """
        Rename a file or folder from ``oldpath`` to ``newpath``, following
        posix conventions.

        :param str oldpath: existing name of the file or folder
        :param str newpath: new name for the file or folder, will be
            overwritten if it already exists

        :raises:
            ``IOError`` -- if ``newpath`` is a folder, posix-rename is not
            supported by the server or something else goes wrong

        :versionadded: 2.2
        """
        oldpath = self._adjust_cwd(oldpath)
        newpath = self._adjust_cwd(newpath)
        self._log(DEBUG, "posix_rename({!r}, {!r})".format(oldpath, newpath))
        self._request(
            CMD_EXTENDED, "posix-rename@openssh.com", oldpath, newpath
        )
```

So it looks like the posix-rename is an extension, not sure which servers implement these.

It seems to work for me on macOS, sure it will also do with OpenSSH on misc. other systems, is there anything else popular as a server?

**Comment by SpiritInAShell** [comment]
> It seems to work for me on macOS, sure it will also do with OpenSSH on misc. other systems, is there anything else popular as a server?

Synology disk station.

1. it seems likely that someone would place a/many repo/s on such a device
2. there are community packages for borg in Synology software center
3. it is possible to run arm binaries from Johann Bauer on older stations with minor adjustments, therefor modern/more powerful intel/arm disk stations will likely also run borg either as a binary or from pip install etc

**Comment by ThomasWaldmann** [comment]
@SpiritInAShell right, misc. NAS system might have special stuff.

One benefit of using sftp protocol by the borg client is that one does not need borg on the repository storage server side, only sftp.

It might be slower due to the small sftp block size (normally individually acknowledged 32KB blocks, IIRC), but I already implemented the 2 tuning measures for that offered by paramiko.
